services:
  zipkin:
    image: openzipkin/zipkin:2.24.3
    hostname: zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  stamp-service:
    hostname: stamp-service
    container_name: stamp-service
    build:
      context: ./poststamp-service
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 50

  address-service:
    hostname: address-service
    container_name: address-service
    build:
      context: ./homeaddress-service
      dockerfile: Dockerfile
    ports:
      - "9091:8080"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 50

  postnl-service:
    hostname: postnl-service
    container_name: postnl-service
    build:
      context: ./postnl-service
      dockerfile: Dockerfile
    ports:
      - "9092:8080"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 50
    depends_on:
      stamp-service:
        condition: service_healthy

  postcard-service:
    hostname: postcard-service
    container_name: postcard-service
    build:
      context: ./postcard-service
      dockerfile: Dockerfile
    ports:
      - "9093:8080"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 50
    depends_on:
      address-service:
        condition: service_healthy
      stamp-service:
        condition: service_healthy
      postnl-service:
        condition: service_healthy